import { expect, test } from "@playwright/test";
import { openProjectSettings } from "../workspace-fixtures";
import { readFile } from "node:fs/promises";
import { createEmptyPart, expectActivePart, expectEmptyParts } from "../workspace-fixtures";

test("project list creates and reopens an empty workbench without sample documents", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/projects");
  await expect(page.getByRole("heading", { name: "Projects", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Project list", exact: true })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "Project", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Discover legacy default project", exact: true })).not.toBeVisible();
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await page.getByRole("textbox", { name: "Project name", exact: true }).fill("Empty design workspace");
  await page.getByRole("dialog").getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page).toHaveURL(/\/projects\/[0-9a-f-]+$/);
  const url = page.url();
  await expect(page.getByRole("heading", { name: "Empty design workspace", exact: true })).toBeVisible();
  await expect(page.getByTestId("empty-project-viewport")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Documents", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Change Request", exact: true })).toBeVisible();
  const readDocuments = () => page.evaluate(async () => {
    const state = await window.pitonWorkspace.read();
    return state.projects.map(project => ({ name: project.name, count: project.documents.length }));
  });
  expect(await readDocuments()).toEqual([{ name: "Empty design workspace", count: 0 }]);
  await expect(page.getByText("Bench Clamp Fixture", { exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByTestId("empty-project-viewport")).toBeVisible();
  expect(await readDocuments()).toEqual([{ name: "Empty design workspace", count: 0 }]);
  await page.getByRole("button", { name: "All projects", exact: true }).click();
  await expect(page.getByRole("row").filter({ hasText: "Empty design workspace" })).toHaveCount(1);
  await page.getByRole("link", { name: "Empty design workspace", exact: true }).click();
  await expect(page).toHaveURL(url);
  await expect(page.getByTestId("empty-project-viewport")).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "Empty design workspace", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});


test("two genuinely empty Parts stay in project tabs and survive close, reload and backup recovery", async ({ page, browser }) => {
  test.setTimeout(60_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const projectName = "Empty Parts project";
  await page.goto("/projects");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  expect(await dialog.evaluate(element => element.matches(":modal"))).toBe(true);
  await dialog.getByRole("textbox", { name: "Project name", exact: true }).fill(projectName);
  await dialog.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("heading", { name: projectName, exact: true })).toBeVisible();
  const projectUrl = page.url();
  await expectEmptyParts(page, projectName, []);
  const shell = await page.locator("main.r7-workbench").elementHandle();
  const firstUrl = await createEmptyPart(page, "First empty Part");
  await expectActivePart(page, projectName, "First empty Part");
  await expectEmptyParts(page, projectName, ["First empty Part"]);
  const beforeTree = await page.evaluate(() => window.pitonWorkspace.read());
  const tree = page.getByRole("tree", { name: "First empty Part model tree" });
  const origin = tree.getByRole("treeitem", { name: "Origin · reference", exact: true });
  await expect(origin).toHaveAttribute("aria-expanded", "false");
  await expect(tree.getByRole("treeitem", { name: "Features (0)", exact: true })).toBeVisible();
  await expect(tree.getByRole("treeitem", { name: "Solid Bodies (0)", exact: true })).toBeVisible();
  const bounds = await tree.boundingBox();
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThan(page.viewportSize()!.height);
  await expect(page.getByRole("button", { name: "Rename project", exact: true })).not.toBeVisible();
  await origin.click();
  await expect(origin).toHaveAttribute("aria-selected", "true");
  await origin.press("ArrowRight");
  const plane = tree.getByRole("treeitem", { name: "Top Plane · reference", exact: true });
  await plane.click();
  await expect(plane).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("region", { name: "Model selection details" })).toContainText("physical grid plane");
  expect(await page.evaluate(() => window.pitonWorkspace.read())).toEqual(beforeTree);
  const secondUrl = await createEmptyPart(page, "Second empty Part");
  await expectActivePart(page, projectName, "Second empty Part");
  await expect(page.getByRole("tablist", { name: "Open documents", exact: true }).getByRole("tab")).toHaveCount(2);
  expect(await shell!.evaluate(element => element.isConnected)).toBe(true);
  await expectEmptyParts(page, projectName, ["First empty Part", "Second empty Part"]);
  await page.getByRole("tab", { name: "First empty Part", exact: true }).click();
  await expect(page).toHaveURL(firstUrl);
  await expectActivePart(page, projectName, "First empty Part");
  await page.getByRole("button", { name: "Close First empty Part", exact: true }).click();
  await expect(page.getByRole("tab", { name: "First empty Part", exact: true })).toHaveCount(0);
  await expect(page).toHaveURL(secondUrl);
  await expectActivePart(page, projectName, "Second empty Part");
  await page.getByRole("button", { name: "Close Second empty Part", exact: true }).click();
  await expect(page).toHaveURL(projectUrl);
  await expect(page.getByRole("tablist", { name: "Open documents", exact: true }).getByRole("tab")).toHaveCount(0);
  expect(await shell!.evaluate(element => element.isConnected)).toBe(true);
  await expect(page.getByTestId("empty-project-viewport")).toBeVisible();
  await expectEmptyParts(page, projectName, ["First empty Part", "Second empty Part"]);
  await page.getByRole("navigation", { name: "Project Files", exact: true }).getByRole("button", { name: "First empty Part", exact: true }).click();
  await expect(page).toHaveURL(firstUrl);
  await expectActivePart(page, projectName, "First empty Part");
  await page.reload();
  await expectActivePart(page, projectName, "First empty Part");
  await expect(page).toHaveURL(firstUrl);
  await expectEmptyParts(page, projectName, ["First empty Part", "Second empty Part"]);
  const pending = page.waitForEvent("download");
  await openProjectSettings(page);
  await page.getByRole("button", { name: "Export project backup", exact: true }).click();
  const backup = await pending;
  const backupPath = (await backup.path())!;
  const packet = JSON.parse(await readFile(backupPath, "utf8"));
  expect(packet.format).toBe("piton-workspace-project/v1");
  expect(packet.project.documents).toHaveLength(2);
  for (const document of packet.project.documents) {
    expect(document.part.revisions).toEqual([]);
    expect(document.part.currentRevisionId).toBeNull();
    expect(document.part.acceptedRevisionId).toBeNull();
    expect(document.revisionIds).toEqual({});
  }
  const context = await browser.newContext();
  try {
    const recovered = await context.newPage();
    recovered.on("pageerror", error => errors.push(error.message));
    await recovered.goto(firstUrl);
    await expect(recovered.getByRole("alert")).toContainText("not found");
    await recovered.getByLabel("Recover project backup").setInputFiles(backupPath);
    await expectActivePart(recovered, projectName, "First empty Part");
    await expect(recovered).toHaveURL(firstUrl);
    await expectEmptyParts(recovered, projectName, ["First empty Part", "Second empty Part"]);
    expect(await recovered.evaluate(async () => (await window.pitonWorkspace.read()).projects[0])).toEqual(packet.project);
    await recovered.getByRole("navigation", { name: "Project Files", exact: true }).getByRole("button", { name: "Second empty Part", exact: true }).click();
    await expect(recovered).toHaveURL(secondUrl);
    await recovered.reload();
    await expectActivePart(recovered, projectName, "Second empty Part");
    await expectEmptyParts(recovered, projectName, ["First empty Part", "Second empty Part"]);
  } finally { await context.close(); }
  expect(errors).toEqual([]);
});
