import { expect, test } from "@playwright/test";
import { openProjectSettings } from "../workspace-fixtures";
import { importBracketFixture, expectActivePart, createEmptyPart, expectEmptyParts } from "../workspace-fixtures";

test("create isolated projects and editable parts; stable routes, history, back and reload", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page).toHaveURL(/\/projects$/);
  await expect(page.getByText("No projects yet.", { exact: false })).toBeVisible();
  const { projectUrl, documentUrl } = await importBracketFixture(page, "Camera mount", "Sensor bracket");
  await expect(page.getByText("Review mesh ready · CAD Z-min 0 on grid", { exact: true })).toBeVisible();
  await page.getByRole("spinbutton", { name: "leg_length_mm", exact: true }).fill("110");
  await page.getByRole("spinbutton", { name: "leg_width_mm", exact: true }).fill("55");
  await page.getByRole("button", { name: "Propose and preview", exact: true }).click();
  await expect(page.getByRole("button", { name: "Commit revision", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Commit revision", exact: true }).click();
  await expect(page.getByRole("complementary", { name: "Project documents and model", exact: true }).getByRole("status")).toContainText("Revision committed");
  await page.reload();
  await expect(page.getByRole("spinbutton", { name: "leg_length_mm", exact: true })).toHaveValue("110");
  await page.getByRole("button", { name: "Revision 1", exact: true }).click();
  const historicalUrl = page.url();
  await expect(page.getByRole("spinbutton", { name: "leg_length_mm", exact: true })).toHaveValue("80");
  await expect(page.getByRole("button", { name: "Propose and preview", exact: true })).toBeDisabled();
  await page.reload();
  await expect(page).toHaveURL(historicalUrl);
  await expect(page.getByRole("spinbutton", { name: "leg_length_mm", exact: true })).toHaveValue("80");
  await page.getByRole("button", { name: "Open current revision", exact: true }).click();
  await expect(page).toHaveURL(documentUrl);
  await page.getByRole("button", { name: "Project overview", exact: true }).click();
  await openProjectSettings(page);
  await page.getByRole("textbox", { name: "Project name", exact: true }).fill("Renamed mount");
  await page.getByRole("button", { name: "Rename project", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Renamed mount", exact: true })).toBeVisible();
  await expect(page).toHaveURL(projectUrl);
  await page.getByRole("button", { name: "All projects", exact: true }).click();
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await page.getByRole("textbox", { name: "Project name", exact: true }).fill("Other project");
  await page.getByRole("dialog").getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Other project", exact: true })).toBeVisible();
  const otherUrl = page.url();
  await createEmptyPart(page, "Other bracket");
  await expectEmptyParts(page, "Other project", ["Other bracket"]);
  await page.goBack();
  await expect(page).toHaveURL(otherUrl);
  await page.goForward();
  await expectActivePart(page, "Other project", "Other bracket");
  await page.goto(documentUrl);
  await expect(page.getByRole("spinbutton", { name: "leg_width_mm", exact: true })).toHaveValue("55");
  await page.goto(otherUrl + "/documents/" + documentUrl.split("/").pop());
  await expect(page.getByRole("alert")).toContainText("scope mismatch");
  await expect(page.getByRole("spinbutton")).toHaveCount(0);
  expect(errors).toEqual([]);
});

test("unknown resources never seed; structured changes validate; archived documents cannot mutate", async ({ page }) => {
  await page.goto("/projects/not-a-project/documents/missing");
  await expect(page.getByRole("alert")).toContainText("Malformed");
  await page.getByRole("button", { name: "All projects", exact: true }).click();
  await expect(page.getByText("No projects yet.", { exact: false })).toBeVisible();
  await importBracketFixture(page, "Draft project", "Draft part");
  await page.getByText("Advanced · structured change request", { exact: true }).click();
  await page.getByRole("textbox", { name: "Structured change request", exact: true }).fill(JSON.stringify({leg_length_mm:120,leg_width_mm:60,base_length_mm:140,base_thickness_mm:9,leg_thickness_mm:10,hole_diameter_mm:7}));
  await page.getByRole("button", { name: "Prepare change proposal", exact: true }).click();
  await expect(page.getByRole("button", { name: "Commit revision", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Commit revision", exact: true }).click();
  await expect(page.getByRole("complementary", { name: "Project documents and model", exact: true }).getByRole("status")).toContainText("Revision committed");
  await page.getByRole("spinbutton", { name: "hole_diameter_mm", exact: true }).fill("99");
  await page.getByRole("button", { name: "Propose and preview", exact: true }).click();
  await expect(page.getByRole("complementary", { name: "Project documents and model", exact: true }).getByRole("status")).toContainText("hole_diameter_mm");
  await expect(page.getByRole("button", { name: "Commit revision", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Project overview", exact: true }).click();
  await openProjectSettings(page);
  await page.getByRole("button", { name: "Archive project", exact: true }).click();
  await page.getByRole("button", { name: "Draft part", exact: true }).click();
  await expect(page.getByRole("button", { name: "Propose and preview", exact: true })).toBeDisabled();
  await expect(page.getByRole("spinbutton", { name: "leg_length_mm", exact: true })).toHaveValue("120");
});
